version: '3'

services:
  textgen:
    image: saladtechnologies/text-generation-webui:pygmalion-2-13b-awq
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

    
          